### ISSUE TITLE
Mouse pointer moves faster than the scroll element

### ISSUE THREAD

**Issue by todoroff** [davidfig/pixi-scrollbox#30] opened 2020-11-25 13:53 UTC
When I click on the scroll rectangle and start scrolling the scroll doesn't keep up with the mouse. In other words for every given mouse move the scroll is less instead of equal. Is that configurable somehow?

**Comment by davidfig** [comment] 2020-11-26 23:49
Is the scrollbox scaled?

**Comment by todoroff** [comment] 2020-11-27 18:05
Nope, I can see the same behavior in the live examples, although it's not as obvious because the scroll distances are fairly short.

**Comment by davidfig** [comment] 2020-12-01 00:05
Ugh. Yeah, I just saw it. This looks like a regression. I'll take a look a the code.

**Comment by davidfig** [comment] 2020-12-01 00:21
Turned out it was not a regression. I had fixed this bug in a cloned implementation, but never changed it in master. It's fixed in 2.2.2.

**Closed as completed** 2020-12-01 01:38 UTC
